### ISSUE TITLE
What is it?

### ISSUE THREAD

**Issue by Davemc380** [HanSolo/digital5#16]
Using a Fenix 5;

Can anyone tell me what the little circle with a line across the middle is (looks like a "no entry" symbol) that sits just above the sunset time?

Also - have done the DarkSky API thing, but don't know where it shows the weather..?

Thanks, 
Dave

**Comment by HanSolo** [comment]
This is the "Do not disturb" icon.
You have to select the weather for either upper left, upper right or bottom field

**Comment by Davemc380** [comment]
Thanks - I see it now. 
Again; best watch face available. Well done and thanks!
