### ISSUE TITLE
Will not load on 5S+

### ISSUE THREAD

**Issue by GAZZ-NYC** [HanSolo/digital5#23]
Watchface will not load at all on the watch, although present on the phone app. 

Watch displays IQ? and that's it.

Thx, G

**Comment by HanSolo** [comment]
Hmm...installed it without problems on my fenix 5x. Can you try to uninstall and reinstall?

**Comment by GAZZ-NYC** [comment]
Wow!  That was fast.

Actually, I did an uninstall/reinstall before I bothered you.

I'd love to fix this - looks perfect for my walks/runs.

Thx, G

**Comment by HanSolo** [comment]
Did it work before? I simply updated the SDK and added support for Vivoactive 3 Music...have to check the emulator.

**Comment by GAZZ-NYC** [comment]
Unfortunately, I didn't have it before. Only noticed it with the current
update.

**Comment by HanSolo** [comment]
I‘m so stupid, just now I see the s in 5s which means your screen size is just 218x218 but this watch face is only made foe watches with 240x240 displays. And that was always the case, sorry.

**Comment by GAZZ-NYC** [comment]
Too bad, but many thanks for solving it.

You may want to change the list of compatible devices.

Best, G
